# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  ruby: circleci/ruby@2.0.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.1.4
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-deps-v1-{{ checksum "omniauth-smart.gemspec" }}
      - run:
          name: Install gem dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gem-deps-v1-{{ checksum "omniauth-smart.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          name: Run RSpec tests
          command: bundle exec rspec

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_test:
    jobs:
      - build_and_test
